{
 "title": "REMP Campaigns AB 2",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "campaign",
    "label": "Campaign",
    "query": "select name as __text, uuid as __value from campaigns"
   },
   {
    "name": "banners",
    "label": "Banners",
    "query": "select banners.name as __text, banners.uuid as __value from banners join campaign_banners cb on (cb.banner_id = banners.id) join campaigns c on (c.id = cb.campaign_id) where c.uuid = '$campaign' group by banners.id"
   },
   {
    "name": "banner_a",
    "label": "Banner",
    "query": "select b.name as __text, b.uuid as __value from banners b join campaign_banners cb on (b.id = cb.banner_id) join campaigns c on cb.campaign_id = c.id where c.uuid = '$campaign' order by weight asc limit 1"
   },
   {
    "name": "banner_b",
    "label": "Banner Varianta B",
    "query": "select b.name as __text, b.uuid as __value from banners b join campaign_banners cb on (b.id = cb.banner_id) join campaigns c on cb.campaign_id = c.id where c.uuid = '$campaign' order by weight asc limit 1, 1"
   },
   {
    "name": "banner_a_name",
    "label": "banner_a_name",
    "query": "select banners.name from banners where banners.uuid = '$banner_a'"
   },
   {
    "name": "banner_b_name",
    "label": "banner_b_name",
    "query": "select banners.name from banners where banners.uuid = '$banner_b'"
   },
   {
    "name": "variants",
    "query": "select cb.uuid from campaign_banners cb join campaigns c on (c.id = cb.campaign_id) where c.uuid = '$campaign' and cb.deleted_at is null group by cb.id"
   },
   {
    "name": "variants_pretty_mysql",
    "label": "Variant",
    "query": "select cb.uuid as __value, cb.variant as __text from campaign_banners as cb where cb.uuid in ($variants) and cb.deleted_at is NULL"
   },
   {
    "name": "proportion",
    "query": "select proportion/100 from campaign_banners where uuid in ($variants_pretty_mysql)"
   },
   {
    "name": "proportion_title",
    "query": "select proportion from campaign_banners where uuid in ($variants_pretty_mysql)"
   }
  ]
 },
 "panels": [
  { "title": "Campaign stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "campaign" },
  {
   "title": "Clicks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT count(\"token\") FROM autogen.\"events_v2\" WHERE \"category\" = 'banner' AND \"action\" = 'click'  AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Started payments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "commerce",
     "query": "SELECT count(\"token\") FROM commerce WHERE \"step\" = 'payment' and \"utm_campaign\" = '$campaign'  AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "utm_campaign", "operator": "=~", "value": "/^$campaign$/" }
     ]
    }
   ]
  },
  {
   "title": "Finished payments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT count(\"token\") FROM commerce WHERE \"step\" = 'purchase' and \"utm_campaign\" = '$campaign' AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Earned",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT sum(\"revenue\") FROM commerce WHERE \"step\" = 'purchase' and \"utm_campaign\" = '$campaign'  AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Campaign",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Shown",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"token\") FROM events_v2 WHERE \"category\" = 'banner' AND \"action\" = 'show' AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clicked",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"token\") FROM events_v2 WHERE \"category\" = 'banner' AND \"action\" = 'click' AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$variants_pretty_mysql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "variants_pretty_mysql" },
  {
   "title": "$variants_pretty_mysql ($proportion_title%)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"token\") FROM events_v2 WHERE \"banner_variant\" = '$variants_pretty_mysql' AND \"category\" = 'banner' AND \"action\" = 'show' AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter GROUP BY time($interval) fill(null)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Shows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"token\") FROM events_v2 WHERE \"banner_variant\" = '$variants_pretty_mysql' AND \"category\" = 'banner' AND \"action\" = 'show' AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Normalized shows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"token\") * $proportion FROM events_v2 WHERE \"banner_variant\" = '$variants_pretty_mysql' AND \"category\" = 'banner' AND \"action\" = 'show' AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT count(\"token\") FROM autogen.\"events_v2\" WHERE \"category\" = 'banner' AND \"action\" = 'click' AND banner_variant = '$variants_pretty_mysql' AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Normalized clicks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT count(\"token\") * $proportion FROM autogen.\"events_v2\" WHERE \"category\" = 'banner' AND \"action\" = 'click' AND banner_variant = '$variants_pretty_mysql' AND (\"campaign_id\"::tag = '$campaign' OR \"utm_campaign\"::tag = '$campaign') AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Finished payments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT count(\"token\") FROM commerce WHERE \"step\" = 'purchase' and \"utm_campaign\" = '$campaign' AND banner_variant = '$variants' AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Normalized finished payments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT count(\"token\") * $proportion FROM commerce WHERE \"step\" = 'purchase' and \"utm_campaign\" = '$campaign' AND banner_variant = '$variants' AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Started payments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "commerce",
     "query": "SELECT count(\"token\") FROM commerce WHERE \"step\" = 'payment' and \"utm_campaign\" = '$campaign' AND banner_variant = '$variants'  AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "utm_campaign", "operator": "=~", "value": "/^$campaign$/" }
     ]
    }
   ]
  },
  {
   "title": "Normalized started payments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "commerce",
     "query": "SELECT count(\"token\") * $proportion FROM commerce WHERE \"step\" = 'payment' and \"utm_campaign\" = '$campaign' AND banner_variant = '$variants'  AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "utm_campaign", "operator": "=~", "value": "/^$campaign$/" }
     ]
    }
   ]
  },
  {
   "title": "Earned",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT sum(\"revenue\") FROM commerce WHERE \"step\" = 'purchase' and \"utm_campaign\" = '$campaign' AND banner_variant = '$variants'  AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Normalized earned",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "events",
     "query": "SELECT sum(\"revenue\") * $proportion FROM commerce WHERE \"step\" = 'purchase' and \"utm_campaign\" = '$campaign' AND banner_variant = '$variants'  AND $timeFilter",
     "select": [
      [
       { "params": [ "token" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "banner" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "show" },
      { "condition": "AND", "key": "campaign_id", "operator": "=~", "value": "/^$campaing$/" }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  }
 ]
}